### ISSUE TITLE
Fatal error when fetching a feed that has an item with guid longer than 255 characters

### ISSUE THREAD

**Issue by philgyford** [xurble/django-feed-reader#13]
Although the `Post` model has a limit of 512 characters for `link`, it only allows 255 characters for `guid`, which is often the same as the link.

I'm currently getting a fatal error when fetching https://feeds.feedburner.com/mcsweeneys because it has an item like this (I've removed the long `description`):

```xml
<item>
  <title>The Estate of Édouard Manet Wishes to Remind Museum Visitors That the Best Way to Prevent Climate Change Is to Throw Bucket After Bucket of Hot Sloppy Soup on the Eminently Mediocre Paintings of That Son of a Bitch Monet</title>
  <dc:creator>Chas Gillespie</dc:creator>
  <description>[REMOVED]</description>
  <pubDate>Mon, 31 Oct 2022 14:00:00 -0400</pubDate>
  <link>https://www.mcsweeneys.net/articles/the-estate-of-edouard-manet-wishes-to-remind-museum-visitors-that-the-best-way-to-prevent-climate-change-is-to-throw-bucket-after-bucket-of-hot-sloppy-soup-on-the-eminently-mediocre-paintings-of-that-son-of-a-bitch-monet</link>
  <guid>https://www.mcsweeneys.net/articles/the-estate-of-edouard-manet-wishes-to-remind-museum-visitors-that-the-best-way-to-prevent-climate-change-is-to-throw-bucket-after-bucket-of-hot-sloppy-soup-on-the-eminently-mediocre-paintings-of-that-son-of-a-bitch-monet</guid>
</item>
```

That `guid` is 256 characters! The traceback when doing a `refreshfeeds` is:

```
...
EXISTING https://www.mcsweeneys.net/articles/if-elected-i-promise-to-murder-you
EXISTING https://www.mcsweeneys.net/articles/horror-movie-titles-according-to-their-side-characters
NEW https://www.mcsweeneys.net/articles/the-estate-of-edouard-manet-wishes-to-remind-museum-visitors-that-the-best-way-to-prevent-climate-change-is-to-throw-bucket-after-bucket-of-hot-sloppy-soup-on-the-eminently-mediocre-paintings-of-that-son-of-a-bitch-monet
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/feeds/utils.py", line 515, in parse_feed_xml
    p  = Post.objects.filter(source=source_feed).filter(guid=guid)[0]
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 446, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(255)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/manage.py", line 22, in <module>
    main()
  File "/code/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/site-packages/feeds/management/commands/refreshfeeds.py", line 11, in handle
    update_feeds(30, self.stdout)
  File "/usr/local/lib/python3.10/site-packages/feeds/utils.py", line 125, in update_feeds
    read_feed(src, output)
  File "/usr/local/lib/python3.10/site-packages/feeds/utils.py", line 350, in read_feed
    (ok,changed) = import_feed(source_feed=source_feed, feed_body=ret.content, content_type=content_type, output=output)
  File "/usr/local/lib/python3.10/site-packages/feeds/utils.py", line 387, in import_feed
    (ok,changed) = parse_feed_xml(source_feed, feed_body, output)
  File "/usr/local/lib/python3.10/site-packages/feeds/utils.py", line 534, in parse_feed_xml
    p.save()
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(255)
```

**Comment by xurble** [comment]
Thank you for this
